description: "General information, infrastructure hosts list and global variables"

environment_info:
  UAT:
    - ""
    - ""
    - ""
    - ""

  PRD:
    - ""
    - ""
    - ""
    - ""
global_vars:
  mimir_prd_url: "https://mimir-prd.company:28540/api/v1/push"
  mimir_uat_url: "https://loki-prd.company:28660/loki/api/v1/push"
  log_glob: "/opt/icom/logs/*.log"
  instance_name: "{{ target }}"